#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
FILES=$(git diff --cached --name-only --diff-filter=ACMR )
echo "$FILES"
[ -z "$FILES" ] && exit 0

# Prettify all selected files
echo "$FILES" | xargs prettier --ignore-unknown --write

echo "$FILES" | xargs git add 
exit 0